version: '3.8'

services:
  dashapp:
    build: .
    ports:
      - "8050:8050"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:wds2025@db:5432/allspark_logs

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: allspark_logs
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
